### ISSUE TITLE
Compatibilty with InfluxDB2.0

### ISSUE THREAD

**Issue by mango63** [janten/factorio-stats#1]
Hi,

i am trying to Run this woth InfluxDB v2.0, i belive the have changed from a login system to token system.

Can you pelase upated for InfluxDB V2.0?

or if it is a simple fix, please tell me what i am doing wrong.

**Comment by janten** [comment]
Hi Peter,

InfluxDB 2.0 shares little more than its name with InfluxDB 1.x, so there is no trivial migration path. There are still supported versions of InfluxDB 1 though, using one of them ist the easiest way to get this project running. If you are using Docker, use the image influxdb:1.8.

**Comment by mango63** [comment]
Hi Jan-Tenberge.

Thanks for the update, ill use InfluxDB 1.8,
